openapi: 3.0.3
info:
  title: Gullar haqida ma`lumotlar
  version: 1.0.0
  description: Yevropa davlatlaridan keltirilgan oliy navli gullar haqida barcha ma`lumotlar
paths:
  /api/v1/:
    get:
      operationId: api_v1_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostSerializers'
          description: ''
    post:
      operationId: api_v1_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostSerializers'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostSerializers'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PostSerializers'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSerializers'
          description: ''
  /api/v1/{id}/:
    get:
      operationId: api_v1_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSerializers'
          description: ''
    put:
      operationId: api_v1_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostSerializers'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostSerializers'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PostSerializers'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSerializers'
          description: ''
    patch:
      operationId: api_v1_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPostSerializers'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPostSerializers'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPostSerializers'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSerializers'
          description: ''
    delete:
      operationId: api_v1_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedPostSerializers:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        rasmi:
          type: string
          format: uri
        nomi:
          type: string
          maxLength: 150
        turi:
          type: string
          maxLength: 100
        qisqacha:
          type: string
        toliq:
          type: string
    PostSerializers:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        rasmi:
          type: string
          format: uri
        nomi:
          type: string
          maxLength: 150
        turi:
          type: string
          maxLength: 100
        qisqacha:
          type: string
        toliq:
          type: string
      required:
      - id
      - nomi
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
