# Generated by Django 4.2.1 on 2023-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0003_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtit',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
