# Generated by Django 4.2.1 on 2023-05-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0004_post_subtit_alter_post_body_alter_post_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='nami',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='qisqacha',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='rasmi',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='toliq',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subtit',
            new_name='turi',
        ),
    ]
