# Generated by Django 4.2.1 on 2023-05-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0006_remove_post_rasmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rasmi',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
