# Generated by Django 4.2.1 on 2023-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0009_rename_nami_post_nomi_alter_post_rasmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rasmi',
            field=models.ImageField(default='', upload_to='static/image'),
        ),
    ]
